apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pm-grafana-hjrc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pm-grafana-hjrc
    app.kubernetes.io/part-of: pm-grafana
  name: pm-grafana-hjrc
  namespace: grafana
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    app.kubernetes.io/instance: pm-grafana-hjrc
status:
  loadBalancer: {}
