apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pm-grafana-hjrc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pm-grafana-hjrc
    app.kubernetes.io/part-of: pm-grafana
  name: pm-grafana-hjrclwdj
spec:
  port:
    targetPort: 3000
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: pm-grafana-hjrc
    weight: 100
status: {}
